### ISSUE TITLE
Stop Detector drops first records after stops

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#296]
When two consecutive stops are detected (two stop sequences with no instant in between), the first instant of the second stop is not included. 

think I have narrowed it down to line 100-102 in the trajectory_stop_detector.py code where we can see that the first record after the stop is not added to the new empty buffer that is used to collect data for the next stop.

https://github.com/movingpandas/movingpandas/blob/bbe66fc08c5be5d138d7bef6c3a9fd6105f9a60a/movingpandas/trajectory_stop_detector.py#L90-L102

**Comment by theOtherJLo** [comment]
I was affected by this bug too. Please can it be fixed!

**Comment by bamacgabhann** [comment]
I am working on an alternative stop detector which I think might be faster, it should solve this too. I need a little time though, it's my grading season and I have a pile of stuff to get through.

**Comment by bamacgabhann** [comment]
### Discussed in https://github.com/movingpandas/movingpandas/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **bamacgabhann** May  1, 2023</sup>
10. I said on one of the issues that I'm working on an alternative faster Stop Detector, I haven't got back to it since then but I will soon. One of the things I intend to add to that (but haven't yet) is the ability to detect stops at specified points, so you could do something like ```detector = mpd.TrajectoryStopDetector(my_traj, gdf)``` and then ```detector.get_stop_points()``` or ```detector.get_stop_time_ranges``` would by default return only the points or time ranges at the locations listed in gdf. 

<sup>Originally posted by **anitagraser** May  1, 2023</sup>
10. Is there a specific spatial tolerance to determine if a detected stop coincides with a point from the input gdf? Or is the input gdf a polygon type?
</div>

My thought was to use the ```max_diameter``` kwarg to specify spatial tolerance. Hadn't considered a polygon gdf but that would be very useful, I think. I should be able to write both in.
